[package]
name = "operator-framework"
version = "0.1.0"
authors = ["Jens Reimann <ctron@dentrassi.de>"]
edition = "2018"
keywords = ["kubernetes", "operator"]
license = "EPL-2.0"
description = "Tools and helpers used to create Kubernetes operators"

[dependencies]

anyhow = "1.0"
log = "0.4"

kube = "0.34"
kube-derive = "0.34"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

sha1 = "0.6"

# todo: find a way to let the user decide the target kubernetes version
k8s-openapi = { version = "0.8", default-features = false, features = ["v1_17"] }
